"""add_documents_table

Revision ID: 165cafc59c14
Revises: c6ace85af995
Create Date: 2026-02-15 09:10:09.930986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165cafc59c14'
down_revision: Union[str, Sequence[str], None] = 'c6ace85af995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'IN_REVIEW', 'REVIEWED', 'REJECTED', 'ARCHIVED', name='documentstatus'), nullable=False),
    sa.Column('category', sa.Enum('COMPLIANCE', 'POLICY', 'AUDIT', 'REGULATORY', 'RISK', 'OPERATIONS', 'GOVERNANCE', 'SECURITY', 'FINANCIAL', 'LEGAL', 'HR', 'OTHER', name='documentcategory'), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index('ix_documents_name', 'documents', ['name'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index('ix_documents_status_category', 'documents', ['status', 'category'], unique=False)
    op.create_index('ix_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_index('ix_documents_status_category', table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('ix_documents_name', table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
