"""add assignments and projects tables

Revision ID: 293bddd4a945
Revises: 86c3eb25451f
Create Date: 2026-02-12 02:39:51.070361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293bddd4a945'
down_revision: Union[str, Sequence[str], None] = '86c3eb25451f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_workflow_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('template_stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='stagestatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_workflow_stages_assignment', 'assignment_workflow_stages', ['assignment_id'], unique=False)
    op.create_index('idx_assignment_workflow_stages_order', 'assignment_workflow_stages', ['assignment_id', 'order'], unique=False)
    op.create_index(op.f('ix_assignment_workflow_stages_assignment_id'), 'assignment_workflow_stages', ['assignment_id'], unique=False)
    op.create_table('assignment_workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('template_step_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='stagestatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_workflow_steps_order', 'assignment_workflow_steps', ['stage_id', 'order'], unique=False)
    op.create_index('idx_assignment_workflow_steps_stage', 'assignment_workflow_steps', ['stage_id'], unique=False)
    op.create_index(op.f('ix_assignment_workflow_steps_stage_id'), 'assignment_workflow_steps', ['stage_id'], unique=False)
    op.create_table('assignment_workflow_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('template_task_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', name='taskstatus'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_workflow_tasks_order', 'assignment_workflow_tasks', ['step_id', 'order'], unique=False)
    op.create_index('idx_assignment_workflow_tasks_status', 'assignment_workflow_tasks', ['status'], unique=False)
    op.create_index('idx_assignment_workflow_tasks_step', 'assignment_workflow_tasks', ['step_id'], unique=False)
    op.create_index(op.f('ix_assignment_workflow_tasks_step_id'), 'assignment_workflow_tasks', ['step_id'], unique=False)
    op.create_table('project_collaborators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', 'COMMENTER', name='collaboratorrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='unique_project_user')
    )
    op.create_index('idx_project_collaborators_user', 'project_collaborators', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_collaborators_project_id'), 'project_collaborators', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_collaborators_user_id'), 'project_collaborators', ['user_id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', name='projecttaskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='projecttaskpriority'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resource_folder_id', sa.UUID(), nullable=True),
    sa.Column('output_folder_id', sa.UUID(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_tasks_assignee', 'project_tasks', ['assignee_id'], unique=False)
    op.create_index('idx_project_tasks_position', 'project_tasks', ['project_id', 'status', 'position'], unique=False)
    op.create_index('idx_project_tasks_project', 'project_tasks', ['project_id'], unique=False)
    op.create_index('idx_project_tasks_status', 'project_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_project_tasks_assignee_id'), 'project_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_status'), 'project_tasks', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'REVIEW', 'COMPLETED', 'ARCHIVED', name='projectstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='projectpriority'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('manager_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('resource_folder_id', sa.UUID(), nullable=True),
    sa.Column('output_folder_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', 'ORGANIZATION', name='projectvisibility'), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_client', 'projects', ['client_id'], unique=False)
    op.create_index('idx_projects_org_status', 'projects', ['organization_id', 'status'], unique=False)
    op.create_index('idx_projects_owner', 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('workflow_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='assignmentpriority'), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_assignments_client', 'workflow_assignments', ['client_id'], unique=False)
    op.create_index('idx_workflow_assignments_org_status', 'workflow_assignments', ['organization_id', 'status'], unique=False)
    op.create_index('idx_workflow_assignments_workflow', 'workflow_assignments', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_assignments_client_id'), 'workflow_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_workflow_assignments_organization_id'), 'workflow_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_assignments_status'), 'workflow_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_assignments_workflow_id'), 'workflow_assignments', ['workflow_id'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_stages_position', 'workflow_stages', ['workflow_id', 'position'], unique=False)
    op.create_index('idx_workflow_stages_workflow', 'workflow_stages', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_stages_workflow_id'), 'workflow_stages', ['workflow_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_steps_position', 'workflow_steps', ['stage_id', 'position'], unique=False)
    op.create_index('idx_workflow_steps_stage', 'workflow_steps', ['stage_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_stage_id'), 'workflow_steps', ['stage_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_tasks_position', 'workflow_tasks', ['step_id', 'position'], unique=False)
    op.create_index('idx_workflow_tasks_step', 'workflow_tasks', ['step_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_step_id'), 'workflow_tasks', ['step_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='workflowstatus'), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_org_status', 'workflows', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflows_organization_id'), 'workflows', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflows_organization_id'), table_name='workflows')
    op.drop_index('idx_workflows_org_status', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_workflow_tasks_step_id'), table_name='workflow_tasks')
    op.drop_index('idx_workflow_tasks_step', table_name='workflow_tasks')
    op.drop_index('idx_workflow_tasks_position', table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_workflow_steps_stage_id'), table_name='workflow_steps')
    op.drop_index('idx_workflow_steps_stage', table_name='workflow_steps')
    op.drop_index('idx_workflow_steps_position', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_stages_workflow_id'), table_name='workflow_stages')
    op.drop_index('idx_workflow_stages_workflow', table_name='workflow_stages')
    op.drop_index('idx_workflow_stages_position', table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index(op.f('ix_workflow_assignments_workflow_id'), table_name='workflow_assignments')
    op.drop_index(op.f('ix_workflow_assignments_status'), table_name='workflow_assignments')
    op.drop_index(op.f('ix_workflow_assignments_organization_id'), table_name='workflow_assignments')
    op.drop_index(op.f('ix_workflow_assignments_client_id'), table_name='workflow_assignments')
    op.drop_index('idx_workflow_assignments_workflow', table_name='workflow_assignments')
    op.drop_index('idx_workflow_assignments_org_status', table_name='workflow_assignments')
    op.drop_index('idx_workflow_assignments_client', table_name='workflow_assignments')
    op.drop_table('workflow_assignments')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.drop_index('idx_projects_org_status', table_name='projects')
    op.drop_index('idx_projects_client', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_tasks_status'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_assignee_id'), table_name='project_tasks')
    op.drop_index('idx_project_tasks_status', table_name='project_tasks')
    op.drop_index('idx_project_tasks_project', table_name='project_tasks')
    op.drop_index('idx_project_tasks_position', table_name='project_tasks')
    op.drop_index('idx_project_tasks_assignee', table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_project_collaborators_user_id'), table_name='project_collaborators')
    op.drop_index(op.f('ix_project_collaborators_project_id'), table_name='project_collaborators')
    op.drop_index('idx_project_collaborators_user', table_name='project_collaborators')
    op.drop_table('project_collaborators')
    op.drop_index(op.f('ix_assignment_workflow_tasks_step_id'), table_name='assignment_workflow_tasks')
    op.drop_index('idx_assignment_workflow_tasks_step', table_name='assignment_workflow_tasks')
    op.drop_index('idx_assignment_workflow_tasks_status', table_name='assignment_workflow_tasks')
    op.drop_index('idx_assignment_workflow_tasks_order', table_name='assignment_workflow_tasks')
    op.drop_table('assignment_workflow_tasks')
    op.drop_index(op.f('ix_assignment_workflow_steps_stage_id'), table_name='assignment_workflow_steps')
    op.drop_index('idx_assignment_workflow_steps_stage', table_name='assignment_workflow_steps')
    op.drop_index('idx_assignment_workflow_steps_order', table_name='assignment_workflow_steps')
    op.drop_table('assignment_workflow_steps')
    op.drop_index(op.f('ix_assignment_workflow_stages_assignment_id'), table_name='assignment_workflow_stages')
    op.drop_index('idx_assignment_workflow_stages_order', table_name='assignment_workflow_stages')
    op.drop_index('idx_assignment_workflow_stages_assignment', table_name='assignment_workflow_stages')
    op.drop_table('assignment_workflow_stages')
    # ### end Alembic commands ###
