"""add_reminders_table

Revision ID: 7050dcdeddb0
Revises: b7ac6bb4f63c
Create Date: 2026-02-13 21:22:22.817254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7050dcdeddb0'
down_revision: Union[str, Sequence[str], None] = 'b7ac6bb4f63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('ASSIGNMENT', 'STAGE', 'STEP', 'TASK', name='reminderentitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('reminder_type', sa.Enum('AUTO_DUE_DATE', 'MANUAL', name='remindertype'), nullable=False),
    sa.Column('offset_label', sa.Enum('THREE_DAYS_BEFORE', 'ONE_DAY_BEFORE', 'ON_DUE_DATE', 'ONE_DAY_OVERDUE', name='reminderoffset'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'SNOOZED', 'DISMISSED', name='reminderstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_entity_id'), 'reminders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reminders_remind_at'), 'reminders', ['remind_at'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_remind_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_entity_id'), table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
