"""add_keycloak_ad_fields_to_users

Revision ID: 86c3eb25451f
Revises: 8a4cd8dd6f72
Create Date: 2026-02-10 10:13:33.745205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c3eb25451f'
down_revision: Union[str, Sequence[str], None] = '8a4cd8dd6f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    authprovider_enum = sa.Enum('LOCAL', 'KEYCLOAK_AD', name='authprovider')
    authprovider_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('auth_provider', authprovider_enum, server_default='LOCAL', nullable=False))
    op.add_column('users', sa.Column('ad_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('keycloak_sub', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_ad_username'), 'users', ['ad_username'], unique=True)
    op.create_index(op.f('ix_users_keycloak_sub'), 'users', ['keycloak_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_keycloak_sub'), table_name='users')
    op.drop_index(op.f('ix_users_ad_username'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'keycloak_sub')
    op.drop_column('users', 'ad_username')
    op.drop_column('users', 'auth_provider')
    sa.Enum(name='authprovider').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
