"""add_clients_contacts_tables

Revision ID: a8b522e8b117
Revises: 293bddd4a945
Create Date: 2026-02-12 17:16:03.736322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b522e8b117'
down_revision: Union[str, Sequence[str], None] = '293bddd4a945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PROSPECT', 'ARCHIVED', name='clientstatus'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_name', 'clients', ['name'], unique=False)
    op.create_index('ix_clients_org_status', 'clients', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='contactstatus'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index('ix_contacts_name', 'contacts', ['first_name', 'last_name'], unique=False)
    op.create_index('ix_contacts_org_status', 'contacts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_status'), 'contacts', ['status'], unique=False)
    op.create_table('client_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'contact_id', name='uq_client_contact')
    )
    op.create_index('ix_client_contacts_client', 'client_contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'], unique=False)
    op.create_index('ix_client_contacts_contact', 'client_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_client_contacts_contact_id'), 'client_contacts', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_contacts_contact_id'), table_name='client_contacts')
    op.drop_index('ix_client_contacts_contact', table_name='client_contacts')
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_index('ix_client_contacts_client', table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_contacts_status'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index('ix_contacts_org_status', table_name='contacts')
    op.drop_index('ix_contacts_name', table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index('ix_clients_org_status', table_name='clients')
    op.drop_index('ix_clients_name', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
