"""add_automation_tables_and_execution_mode

Revision ID: c6ace85af995
Revises: a1b2c3d4e5f6
Create Date: 2026-02-15 06:32:34.540252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ace85af995'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('template_dependency_id', sa.UUID(), nullable=True),
    sa.Column('dependency_type', sa.Enum('INTRA_FIRM', 'CLIENT_FIRM', 'TASK_TO_TASK', 'STEP_TO_STEP', 'STAGE_TO_STAGE', name='dependencytype'), nullable=False),
    sa.Column('source_entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('is_satisfied', sa.Boolean(), nullable=False),
    sa.Column('satisfied_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asgn_dep_assignment', 'assignment_dependencies', ['assignment_id'], unique=False)
    op.create_index('idx_asgn_dep_target', 'assignment_dependencies', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index(op.f('ix_assignment_dependencies_assignment_id'), 'assignment_dependencies', ['assignment_id'], unique=False)
    op.create_table('automation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_EMAIL', 'SEND_IN_APP', 'ASSIGN_TASK', 'UPDATE_STATUS', 'CREATE_TASK', 'NOTIFY_TEAM', 'WEBHOOK', name='actiontype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_action_rule', 'automation_actions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_automation_actions_rule_id'), 'automation_actions', ['rule_id'], unique=False)
    op.create_table('automation_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'GREATER_THAN', 'LESS_THAN', 'IN_LIST', 'IS_EMPTY', 'IS_NOT_EMPTY', name='conditionoperator'), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_cond_rule', 'automation_conditions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_automation_conditions_rule_id'), 'automation_conditions', ['rule_id'], unique=False)
    op.create_table('automation_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('trigger_event', sa.String(length=100), nullable=False),
    sa.Column('trigger_entity_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_entity_id', sa.UUID(), nullable=True),
    sa.Column('conditions_met', sa.Boolean(), nullable=False),
    sa.Column('condition_details', sa.JSON(), nullable=True),
    sa.Column('actions_executed', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_exec_log_assignment', 'automation_execution_logs', ['assignment_id'], unique=False)
    op.create_index('idx_auto_exec_log_rule', 'automation_execution_logs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_automation_execution_logs_assignment_id'), 'automation_execution_logs', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_automation_execution_logs_rule_id'), 'automation_execution_logs', ['rule_id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', name='automationrulestatus'), nullable=False),
    sa.Column('trigger_event', sa.Enum('STAGE_ENTERED', 'STAGE_COMPLETED', 'STEP_ENTERED', 'STEP_COMPLETED', 'TASK_COMPLETED', 'TASK_ASSIGNED', 'ASSIGNMENT_CREATED', 'ASSIGNMENT_ACTIVATED', 'ASSIGNMENT_COMPLETED', 'DUE_DATE_APPROACHING', name='triggerevent'), nullable=False),
    sa.Column('trigger_entity_type', sa.String(length=50), nullable=True),
    sa.Column('trigger_entity_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auto_rules_trigger', 'automation_rules', ['trigger_event'], unique=False)
    op.create_index('idx_auto_rules_workflow', 'automation_rules', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_automation_rules_workflow_id'), 'automation_rules', ['workflow_id'], unique=False)
    op.create_table('recurring_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY', 'CUSTOM', name='recurrencefrequency'), nullable=False),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('default_priority', sa.String(length=50), nullable=False),
    sa.Column('auto_activate', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_sched_next_run', 'recurring_schedules', ['is_active', 'next_run_at'], unique=False)
    op.create_index('idx_rec_sched_org', 'recurring_schedules', ['organization_id'], unique=False)
    op.create_index('idx_rec_sched_workflow', 'recurring_schedules', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_recurring_schedules_organization_id'), 'recurring_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recurring_schedules_workflow_id'), 'recurring_schedules', ['workflow_id'], unique=False)
    op.create_table('workflow_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('INTRA_FIRM', 'CLIENT_FIRM', 'TASK_TO_TASK', 'STEP_TO_STEP', 'STAGE_TO_STAGE', name='dependencytype'), nullable=False),
    sa.Column('source_entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wf_dep_source', 'workflow_dependencies', ['source_entity_type', 'source_entity_id'], unique=False)
    op.create_index('idx_wf_dep_target', 'workflow_dependencies', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index('idx_wf_dep_workflow', 'workflow_dependencies', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_dependencies_workflow_id'), 'workflow_dependencies', ['workflow_id'], unique=False)
    op.create_table('workflow_sops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wf_sop_entity', 'workflow_sops', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_wf_sop_workflow', 'workflow_sops', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_sops_workflow_id'), 'workflow_sops', ['workflow_id'], unique=False)
    op.add_column('assignment_workflow_stages', sa.Column('execution_mode', sa.String(length=50), nullable=False))
    op.add_column('assignment_workflow_steps', sa.Column('execution_mode', sa.String(length=50), nullable=False))
    op.add_column('workflow_stages', sa.Column('execution_mode', sa.String(length=50), nullable=False))
    op.add_column('workflow_steps', sa.Column('execution_mode', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'execution_mode')
    op.drop_column('workflow_stages', 'execution_mode')
    op.drop_column('assignment_workflow_steps', 'execution_mode')
    op.drop_column('assignment_workflow_stages', 'execution_mode')
    op.drop_index(op.f('ix_workflow_sops_workflow_id'), table_name='workflow_sops')
    op.drop_index('idx_wf_sop_workflow', table_name='workflow_sops')
    op.drop_index('idx_wf_sop_entity', table_name='workflow_sops')
    op.drop_table('workflow_sops')
    op.drop_index(op.f('ix_workflow_dependencies_workflow_id'), table_name='workflow_dependencies')
    op.drop_index('idx_wf_dep_workflow', table_name='workflow_dependencies')
    op.drop_index('idx_wf_dep_target', table_name='workflow_dependencies')
    op.drop_index('idx_wf_dep_source', table_name='workflow_dependencies')
    op.drop_table('workflow_dependencies')
    op.drop_index(op.f('ix_recurring_schedules_workflow_id'), table_name='recurring_schedules')
    op.drop_index(op.f('ix_recurring_schedules_organization_id'), table_name='recurring_schedules')
    op.drop_index('idx_rec_sched_workflow', table_name='recurring_schedules')
    op.drop_index('idx_rec_sched_org', table_name='recurring_schedules')
    op.drop_index('idx_rec_sched_next_run', table_name='recurring_schedules')
    op.drop_table('recurring_schedules')
    op.drop_index(op.f('ix_automation_rules_workflow_id'), table_name='automation_rules')
    op.drop_index('idx_auto_rules_workflow', table_name='automation_rules')
    op.drop_index('idx_auto_rules_trigger', table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_automation_execution_logs_rule_id'), table_name='automation_execution_logs')
    op.drop_index(op.f('ix_automation_execution_logs_assignment_id'), table_name='automation_execution_logs')
    op.drop_index('idx_auto_exec_log_rule', table_name='automation_execution_logs')
    op.drop_index('idx_auto_exec_log_assignment', table_name='automation_execution_logs')
    op.drop_table('automation_execution_logs')
    op.drop_index(op.f('ix_automation_conditions_rule_id'), table_name='automation_conditions')
    op.drop_index('idx_auto_cond_rule', table_name='automation_conditions')
    op.drop_table('automation_conditions')
    op.drop_index(op.f('ix_automation_actions_rule_id'), table_name='automation_actions')
    op.drop_index('idx_auto_action_rule', table_name='automation_actions')
    op.drop_table('automation_actions')
    op.drop_index(op.f('ix_assignment_dependencies_assignment_id'), table_name='assignment_dependencies')
    op.drop_index('idx_asgn_dep_target', table_name='assignment_dependencies')
    op.drop_index('idx_asgn_dep_assignment', table_name='assignment_dependencies')
    op.drop_table('assignment_dependencies')
    # ### end Alembic commands ###
