"""add_agent_tables

Revision ID: fbf42b4aa5f0
Revises: 7daf66cfdc7a
Create Date: 2026-02-12 19:53:11.650710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf42b4aa5f0'
down_revision: Union[str, Sequence[str], None] = '7daf66cfdc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_task_agent_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', name='executionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('backend_provider', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_exec_agent', 'agent_executions', ['agent_id'], unique=False)
    op.create_index('idx_agent_exec_ata', 'agent_executions', ['assignment_task_agent_id'], unique=False)
    op.create_index('idx_agent_exec_status', 'agent_executions', ['status'], unique=False)
    op.create_index('idx_agent_exec_task', 'agent_executions', ['task_id'], unique=False)
    op.create_index('idx_agent_exec_triggered', 'agent_executions', ['triggered_by'], unique=False)
    op.create_index(op.f('ix_agent_executions_agent_id'), 'agent_executions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_assignment_task_agent_id'), 'agent_executions', ['assignment_task_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_task_id'), 'agent_executions', ['task_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('agent_type', sa.Enum('DOCUMENT_INTELLIGENCE', 'SEARCH', 'EXTRACTION', 'VALIDATION', 'CUSTOM', name='agenttype'), nullable=False),
    sa.Column('backend_provider', sa.String(length=100), nullable=False),
    sa.Column('backend_config', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DEPRECATED', name='agentstatus'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_org', 'agents', ['organization_id'], unique=False)
    op.create_index('idx_agents_status', 'agents', ['status'], unique=False)
    op.create_index('idx_agents_type', 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_organization_id'), 'agents', ['organization_id'], unique=False)
    op.create_table('assignment_task_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('template_agent_id', sa.UUID(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='agentassignmentstatus'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('task_config', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.String(length=2000), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('last_execution_id', sa.UUID(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assign_task_agents_agent', 'assignment_task_agents', ['agent_id'], unique=False)
    op.create_index('idx_assign_task_agents_order', 'assignment_task_agents', ['task_id', 'order'], unique=False)
    op.create_index('idx_assign_task_agents_status', 'assignment_task_agents', ['status'], unique=False)
    op.create_index('idx_assign_task_agents_task', 'assignment_task_agents', ['task_id'], unique=False)
    op.create_index(op.f('ix_assignment_task_agents_agent_id'), 'assignment_task_agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_assignment_task_agents_task_id'), 'assignment_task_agents', ['task_id'], unique=False)
    op.create_table('workflow_task_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('task_config', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wf_task_agents_agent', 'workflow_task_agents', ['agent_id'], unique=False)
    op.create_index('idx_wf_task_agents_position', 'workflow_task_agents', ['task_id', 'position'], unique=False)
    op.create_index('idx_wf_task_agents_task', 'workflow_task_agents', ['task_id'], unique=False)
    op.create_index(op.f('ix_workflow_task_agents_agent_id'), 'workflow_task_agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_workflow_task_agents_task_id'), 'workflow_task_agents', ['task_id'], unique=False)
    op.drop_constraint(op.f('fk_projects_client_id'), 'projects', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_projects_client_id'), 'projects', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_workflow_task_agents_task_id'), table_name='workflow_task_agents')
    op.drop_index(op.f('ix_workflow_task_agents_agent_id'), table_name='workflow_task_agents')
    op.drop_index('idx_wf_task_agents_task', table_name='workflow_task_agents')
    op.drop_index('idx_wf_task_agents_position', table_name='workflow_task_agents')
    op.drop_index('idx_wf_task_agents_agent', table_name='workflow_task_agents')
    op.drop_table('workflow_task_agents')
    op.drop_index(op.f('ix_assignment_task_agents_task_id'), table_name='assignment_task_agents')
    op.drop_index(op.f('ix_assignment_task_agents_agent_id'), table_name='assignment_task_agents')
    op.drop_index('idx_assign_task_agents_task', table_name='assignment_task_agents')
    op.drop_index('idx_assign_task_agents_status', table_name='assignment_task_agents')
    op.drop_index('idx_assign_task_agents_order', table_name='assignment_task_agents')
    op.drop_index('idx_assign_task_agents_agent', table_name='assignment_task_agents')
    op.drop_table('assignment_task_agents')
    op.drop_index(op.f('ix_agents_organization_id'), table_name='agents')
    op.drop_index('idx_agents_type', table_name='agents')
    op.drop_index('idx_agents_status', table_name='agents')
    op.drop_index('idx_agents_org', table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_executions_task_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_assignment_task_agent_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_id'), table_name='agent_executions')
    op.drop_index('idx_agent_exec_triggered', table_name='agent_executions')
    op.drop_index('idx_agent_exec_task', table_name='agent_executions')
    op.drop_index('idx_agent_exec_status', table_name='agent_executions')
    op.drop_index('idx_agent_exec_ata', table_name='agent_executions')
    op.drop_index('idx_agent_exec_agent', table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
